# Code Example: Singular Value Decomposition

[![View on GitHub](https://img.shields.io/badge/GitHub-181717?logo=github&logoColor=white)](https://github.com/bu-cds-omds/dx601-examples/blob/main/week12/code_example_singular_value_decomposition.ipynb)
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/bu-cds-omds/dx601-examples/blob/main/week12/code_example_singular_value_decomposition.ipynb)



In [ ]:
import numpy as np

A = np.array([[0.5, 1.0], [1.0, 0.5]])
A

array([[0.5, 1. ],
       [1. , 0.5]])

The singular value decomposition can be computed with the `np.linalg.svd` function from NumPy.
It returns a NumPy array for each of the components of the decomposition $\mathbf{U} \mathbf{\Sigma} \mathbf{V}^\top$.

In [ ]:
U, s, Vt = np.linalg.svd(A)

In [ ]:
U

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

The $\mathbf{\Sigma}$ matrix is returned as a vector `s` with just the diagonal entries.

In [ ]:
s

array([1.5, 0.5])

NumPy's `np.diag` function will return the full diagonal matrix $\mathbf{\Sigma}$.

In [ ]:
np.diag(s)

array([[1.5, 0. ],
       [0. , 0.5]])

The transposed $\mathbf{V}$ matrix is returned for convenience, but the original $\mathbf{V}$ is easily available.

In [ ]:
Vt

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [ ]:
Vt.T

array([[-0.70710678,  0.70710678],
       [-0.70710678, -0.70710678]])